### ISSUE TITLE
User can select art periods they are interested in

### ISSUE THREAD

**Issue by khan-osama** [osamaakhan61/ajax-project#1]
## 💰 Motivation

The user needs to be able to choose their interests in order for the app to recommend art based on the user's preferences.

## 📐 Plan

Allow users to select from a list of art history periods to curate art recommendations.

## 🖼️ Wireframe

![Main Screen](https://user-images.githubusercontent.com/63980419/108884665-b622cc00-75bb-11eb-9c03-1800568a287b.png)
![Query Screen](https://user-images.githubusercontent.com/63980419/108884663-b58a3580-75bb-11eb-8b00-729b239de5e6.png)
![Confirmation Screen](https://user-images.githubusercontent.com/63980419/108884657-b4590880-75bb-11eb-8e74-84c3e7555938.png)

## ✅ Task List

- [x] Create background image for main screen
- [x] Add mobile responsive functionality
- [x] Add HTML and CSS for title and subtitle
- [x] Create 'Get Started' button
- [x] Add font-family Playfair Display from Google Fonts
- [x] Make button clickable
- [x] Add functionality to hide main screen when 'Get Started' button is clicked
- [x] Display query screen when main screen is hidden
- [x] Add HTML for Query Screen
- [x] Add buttons for each century
- [x] Fix mobile responsiveness
- [x] Add eventlistener to buttons for selection
- [x] Make requirement for user to choose minimum one century
- [x] Add CSS for page
- [x] Hide Query Screen after user chooses art period
- [x] Display Confirmation Screen
- [x] Fix bug for 'get started' button showing up
- [x] Add HTML / CSS for Confirmation screen
- [x] Add two buttons for confirmation or going back
- [x] Take user back to Query screen if going back button is clicked
- [x] Hide Confirmation screen if user clicks 'Show me art!'
- [x] Remove any excess CSS
- [x] Confirm functionality on Desktop and mobile screen
- [x] Fix any bugs
