### ISSUE TITLE
User can like / dislike art

### ISSUE THREAD

**Issue by khan-osama** [osamaakhan61/ajax-project#2]
## 💰 Motivation

Users should be able to save art that gets recommended to them if they like it for viewing later.

## 📐 Plan

Allow users to click on a 'plus' button in order to save to a list for later.

## 🖼️ Wireframe

![Choosing Art Screen](https://user-images.githubusercontent.com/63980419/108886285-a5735580-75bd-11eb-95ef-5acb78299027.png)

## ✅ Task List

- [x] Create DOM skeleton in JavaScript
- [x] Dynamically create DOM elements on page load
- [x] Grab appropriate art data based user century selection
- [x] Store data in variable
- [x] Insert Image link into correct elements
- [x] Insert artist name and year into correct elements
- [x] Dynamically change data to match century chosen
- [x] Create navigation pane
- [x] Add navigation pane icons
- [x] Add CSS to navigation pane
- [x] Added plus button
- [x] Hide add-art page when clicking on search or liked list icons in navigation pane
- [x] display add-art page when clicking on home page
- [x] Keep data consistent even when page is refreshed on add art page
- [x] Make sure page is mobile responsive 
- [x] Remove any excess CSS
- [x] Check for CSS class names
- [x] Fix any bugs
