### ISSUE TITLE
User can view art pieces that have picture of the art, artist name and description

### ISSUE THREAD

**Issue by khan-osama** [osamaakhan61/ajax-project#3]
## 💰 Motivation

Users should be able to take a closer look at art they like in depth.

## 📐 Plan

Allow users to click into art to read title, artist name, year and description.

## 🖼️ Wireframe

![View Screen](https://user-images.githubusercontent.com/63980419/108886407-c9369b80-75bd-11eb-99f7-2f612c79dc1e.png)

## ✅ Task List

- [x] When user clicks on art piece, hide list
- [x] Grab correct data
- [x] Enlarge art picture, name and year and plus icon
- [x] Add description
- [x] Check CSS
- [x] Fix any bugs
- [x] Check for mobile responsiveness
