### ISSUE TITLE
User can view liked art in a saved list

### ISSUE THREAD

**Issue by khan-osama** [osamaakhan61/ajax-project#4]
## 💰 Motivation

Users should be able to refer to art they liked previously any time in a list.

## 📐 Plan

Allow users to navigate to a page that contains all art elements previously liked by the user and display in a list while also allowing them to remove if they wanted.

## 🖼️ Wireframe

![Liked Art Screen](https://user-images.githubusercontent.com/63980419/108886668-187ccc00-75be-11eb-9054-5bed6ea82574.png)

## ✅ Task List

- [x] Save any liked art into data model
- [x] Pull up data when clicking on liked page list
- [x] Render data the same as art list
- [x] allow user to remove art and remove from the page DOM
- [x] allow users to click in to view the art
- [x] Check CSS
- [x] Fix any bugs
- [x] Check mobile responsiveness
