### ISSUE TITLE
User can search for art by artist name

### ISSUE THREAD

**Issue by khan-osama** [osamaakhan61/ajax-project#5]
## 💰 Motivation

Users should be able to look for an artist's work by searching the artist name.

## 📐 Plan

Allow users to go to a search page and type in artist name. The search query will bring up a list of art by that artist which also allows the user to add the art or remove if already added. The search query can display no results if the query returns nothing.

## 🖼️ Wireframe

![Search Screen](https://user-images.githubusercontent.com/63980419/108886980-7c9f9000-75be-11eb-9c9d-10340842ae73.png)

![Search Query Page](https://user-images.githubusercontent.com/63980419/108886962-77dadc00-75be-11eb-8982-0e31c149e567.png)
![No Results Screen](https://user-images.githubusercontent.com/63980419/108886948-727d9180-75be-11eb-8c30-29d9b7b34950.png)

## ✅ Task List

- [x] Create HTML for search page
- [x] Create HTML for search bar
- [x] Add default text into search bar
- [x] Add CSS styling to search bar
- [x] Hide search bar when user presses enter
- [x] Run API query using user input
- [x] Pull up API data
- [x] Display message if no API data is found
- [x] Render DOM tree for relevant API data
- [x] Fix any bugs
- [x] Check for mobile responsiveness
